services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "8081:80"
    
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis
      - redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10
  
volumes:
  redis:
    driver: local