services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - ./docker-db/:/app/docker-db
    ports:
      - "8081:80"
    networks:
      - app-network

  sqlite:
    image: keinos/sqlite3:latest
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    volumes:
      - ./docker-db/database.db:/root/db/database.db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
